server:
  port: 8080

grpc:
  server:
    port: 9090

spring:
  application:
    name: content-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    prefer-ip-address: true
    hostname: auth-api
  client:
    service-url:
      defaultZone: http://service-discovery:8000/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.hibernate.sql: DEBUG

jwt:
  secret: ${JWT_SECRET}