apiVersion: v1
kind: Service
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: 9090
      protocol: TCP
  selector:
    app: content-api