replicaCount: 1

imagePullSecret: regcred

image:
  repository: sangsiklog-registry.kr.ncr.ntruss.com/auth-api-amd64
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi