server:
  port: 8080

spring:
  application:
    name: sangsiklog-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: lb://auth-api
          predicates:
            - Path=/auth/**
            - Method=POST,GET,OPTIONS
          filters:
            - RewritePath=/auth$, /v1/auth
            - RewritePath=/auth/(?<segment>.*), /v1/auth/${segment}
        - id: graphql-route
          uri: lb://graphql-service
          predicates:
            - Path=/graphql
            - Method=POST,GET,OPTIONS
          filters:
            - AuthenticationFilter

      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:8080"
            allowed-methods:
              - GET
              - POST
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  instance:
    prefer-ip-address: true
    hostname: sangsiklog-gateway
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true

    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG