apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-monitoring-config
  labels:
    app: prometheus-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - "alertmanager:9093"

    rule_files:
      - "/etc/prometheus/rules/alert.rules"

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['localhost:9100']

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['localhost:8080']

      - job_name: 'service-discovery'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['service-discovery:8000']

      - job_name: 'auth-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-api:8080']

      - job_name: 'content-api'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['content-api:8080']

      - job_name: 'graphql-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['graphql-service:8080']

      - job_name: 'sangsiklog-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['sangsiklog-gateway:8080']

  alert.rules: |
    groups:
    - name: service_down_rule
      rules:

      - alert: service_down
        expr: up == 0
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ "{{" }} $labels.instance {{ "}}" }} down"
          description: "{{ "{{" }} $labels.instance {{ "}}" }} of job {{ "{{" }} $labels.job {{ "}}" }} has been down for more than 2 minutes."

      - alert: high_load
        expr: node_load1 > 0.5
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ "{{" }} $labels.instance {{ "}}" }} under high load"
          description: "{{ "{{" }} $labels.instance {{ "}}" }} of job {{ "{{" }} $labels.job {{ "}}" }} is under high load."

  alertmanager.yml: |
    route:
      receiver: 'slack'

    receivers:
      - name: 'slack'