apiVersion: v1
kind: Service
metadata:
  name: prometheus-monitoring
  labels:
    app: prometheus-monitoring
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prometheus
      port: {{ .Values.service.prometheus.port }}
      targetPort: 9090
      protocol: TCP
    - name: node-exporter
      port: {{ .Values.service.nodeExporter.port }}
      targetPort: 9100
      protocol: TCP
    - name: cadvisor
      port: {{ .Values.service.cadvisor.port }}
      targetPort: 8080
      protocol: TCP
    - name: alertmanager
      port: {{ .Values.service.alertmanager.port }}
      targetPort: 9093
      protocol: TCP
  selector:
    app: prometheus-monitoring