apiVersion: v1
kind: Service
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: auth-api