replicaCount: 1

imagePullSecret: regcred

image:
  repository: grafana/grafana
  tag: 11.1.4
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi