replicaCount: 1

imagePullSecret: regcred

image:
  repository: sangsiklog-registry.kr.ncr.ntruss.com/content-api-amd64
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 9090

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi