replicaCount: 1

imagePullSecret: regcred

image:
  repository: sangsiklog-registry.kr.ncr.ntruss.com/content-api-amd64
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  httpPort: 8080
  grpcPort: 9090

resources:
  limits:
    cpu: 600m
    memory: 1Gi
  requests:
    cpu: 300m
    memory: 512Mi