replicaCount: 1

imagePullSecret: regcred

image:
  repository: sangsiklog-registry.kr.ncr.ntruss.com/graphql-service-amd64
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 800m
    memory: 1Gi
  requests:
    cpu: 400m
    memory: 512Mi