replicaCount: 1

imagePullSecret: regcred

image:
  repository: openzipkin/zipkin
  tag: 3.4.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9411

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi