replicaCount: 1

imagePullSecret: regcred

image:
  repository: openzipkin/zipkin
  tag: v3.4.1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9411

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi