server:
  port: 8081

spring:
  application:
    name: graphql
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      inspection:
        enabled: true

http:
  user-service:
    base-url: http://auth-api/v1/users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true