server:
  port: 8000

spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: localhost
    registry:
      default-open-for-traffic-count: 1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    region: default

  server:
    renewal-percent-threshold: 0
    enable-self-preservation: true