apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  labels:
    app: graphql-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: graphql-service