apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: zipkin
      port: {{ .Values.service.port }}
      targetPort: zipkin
      protocol: TCP
  selector:
    app: zipkin